### ISSUE TITLE
Automatically configure from a single URL

### ISSUE THREAD

**Issue by graingert** [bopen/react-jsonschema-form-async#2]
I have a URL that returns `{ schema, uiSchema, errors }` and accepts a multipart `formData`, and commits any valid data to the database

I'd like to be able to configure an such a form in one go:

```js
<AutoForm api="https://api.example.com/entity/" fetch={fetch} />
```

**Comment by keul** [comment]
Sorry, no idea what `AutoForm` is. Maybe you opened the issue in the wrong repo?

**Comment by graingert** [comment]
I'm suggesting this as a new feature

**Comment by keul** [comment]
@graingert sorry, I misunderstood your question then.

I think that such feature request should go in the inner react-jsonschema-form codebase then.
This repo is only about making validation async while you are suggesting a form that automatically configure itself from a remote URL.

BTW: you can obtain this with a simple wrapper I think.

**Comment by graingert** [comment]
Yeah I know I've got one. I'm suggesting to contribute it
